### ISSUE TITLE
Simple Clans is generating offline mode UUIDs when using BungeeCord

### ISSUE THREAD

**Issue by i9hdkill** [phaed420/SimpleClans#228]
We are using a BungeeCord setup.
We had Simple clans Legacy installed.
Now I switched to Simple Clans 2 (recommend build from jenkins server)
When I launched the server, it adds the UUIDs to my mysql table.
Because of BungeeCord our server is running in offline mode. I guess because of that, simpleclan took offline UUIDs and not the online ones...
The thing is, now every player is in no guild because simpleclan doesn't know that player (onlineuuid =/ offlineuuid)
I had to use my backup table from the legacy version.
Could you fix bungeecord mode?
I found a config option, but when I set bungeecord to true, its gets back to false every serverstart.

**Comment by phaed420** [comment]
Set ip_foprward to true in bungee config

http://www.spigotmc.org/threads/solved-getting-uuids.13654/
