### ISSUE TITLE
Player killing other Player causes server crash

### ISSUE THREAD

**Issue by m1enkrafftman** [phaed420/SimpleClans#235]
As the title states. No error output to console that is known. Disabling plugin stops error from happening. Running only this plugin still causes crashes. Servers is running latest Spigot.

**Comment by viper55x** [comment]
Same problem here, Awesome plugin but had to be removed due to causing crashes :) cant wait for a stable version. FACTIONS SUX!

**Comment by phaed420** [comment]
fixed on latest build
