### ISSUE TITLE
Server crash / config broken / Pex prefix / nickname wiped

### ISSUE THREAD

**Issue by Unviewed** [phaed420/SimpleClans#236]
This plugin screws up the pex prefixes, the second you join a clan, the prefix is gone. Once you join a clan, nicknames are also wiped. The config file does not work on bit, it reloads it no matter what. 

When a person leaves a clan, the prefix is NOT restored, the nickname is NOT restored. 

Also, the server tends to crash upon pvping at random times.

Spigot 1.7/1.8 multi-minecraft-client supported.

**Comment by viper55x** [comment]
to fix your prefixes in the config set "chat-compatibility-mode: true"
I also have the same problem with server crashing from PVP, Im sure the Dev's are doing their best :)
