### ISSUE TITLE
[URGENT] Simpleclans causing large lagspikes

### ISSUE THREAD

**Issue by Her-Craving** [phaed420/SimpleClans#238]
Simpleclans Legacy is causing large lagspikes. Here is my timings report: http://timings.aikar.co/?url=9779880

In case it gets deleted, here are the two events that are causing the most damage:

1.10%	1,035.31%	3.62 s	517.66 ms	0.0	0.0k	Task: SCPlayerListener$1(Single) 1.09%	900.38% 3.60 s	450.19 ms	0.0	0.0k	SCPlayerListener::onPlayerQuit(PlayerQuitEvent)

This is causing huge lagspikes and I will be forced to remove the plugin soon if it's not fixed. I hope you can fix this ASAP. Please add me on skype for easier communication: Bla_Saige433 .

**Comment by phaed420** [comment]
try the latest dev build, i removed the task on the player listener

**Comment by Her-Craving** [comment]
Is this for legacy?

**Comment by phaed420** [comment]
Yep, legacy is the only version going forward.  The other version that was being built by a contributor was too bug laden, badly designed, and unstable to fix, had to revert back to the legacy version.
