### ISSUE TITLE
Server Crash when someone kills someone else.

### ISSUE THREAD

**Issue by Skyyofficial** [phaed420/SimpleClans#240]
I will post it in 2 pastebin links because the second crash log is over 1000 lines long.

Console output:
NOTE: I will post what happened before if this could help.

http://pastebin.com/ZB3RyeYP

Hs_err_pid24797.log:

http://pastebin.com/6JUFKchF

Well i hope this will help you and could be fixed ASAP because all really like and need this plugin for our pvp server :)

**Comment by phaed420** [comment]
Fixed
