### ISSUE TITLE
Can't see Clan Prefix?

### ISSUE THREAD

**Issue by Onewingseraphim** [phaed420/SimpleClans#243]
I'm using PEX and EssentialsChat and I can't seem to get the Clan Prefix to appear in chat unless that player is OP, I've tried testing with permissions by giving them Simpleclans.* but  that doesn't work, I've also tried HeroChat and MChat but nothing seems to be working unless you're OP. I do have "chat compatibility mode: true " as well.

**Comment by phaed420** [comment]
Do you have chat-compatibility-mode: true in the config?

**Comment by Onewingseraphim** [comment]
Yes I do

**Comment by phaed420** [comment]
Have you added {clan} in the chat config?

**Comment by phaed420** [comment]
Think your issue is with your chat plugin config.

**Comment by Onewingseraphim** [comment]
I tried using {CLAN} but it didn't seem to do anything, is essentialschat
compatible with the plugin?

**Comment by phaed420** [comment]
Yep.  Use EssentialsChat default config and it will work.  Then track back and see why your setup is not working.

**Comment by Onewingseraphim** [comment]
I reset the entire config and it still didn't work, I'm confused to why it
only works when I'm OP but not any other time. I would've thought that if
it were a chat configuration error then it wouldn't work as OP either its
been acting like a permissions issue but I don't know what it would be.

**Comment by phaed420** [comment]
Maybe you have another plugin interfering.  Try removing all others then try again.

**Comment by Onewingseraphim** [comment]
Okay I found the source of the issue and it was a plugin called Swear
Filter, thank you so much for the help! I love you plugins, I appreciate
all your hard work. :)

**Comment by phaed420** [comment]
Glad I could be of help :)
