### ISSUE TITLE
ChatControl Tag Integration

### ISSUE THREAD

**Issue by HeroWaar** [phaed420/SimpleClans#245]
Hi,

First, thanks for the amazing plugin...
Now let's go to the issue, using Chatcontrol 5.0.6 the clan tag should be showing after the local/global or with the player prefix but it appears before everything, can you create a compatibility for this plugin too?

Look the example here: http://i.imgur.com/6Be9om4.png

Once again, amazing plugin thanks!
(Sorry for my poor english)

Regards,
HeroWaar

**Comment by phaed420** [comment]
Created a pull request to ChatControl with the SimpleClans integration code.  It's in kangarko's hands now.
