### ISSUE TITLE
need help with clan tag in herochat

### ISSUE THREAD

**Issue by Longhair1996** [phaed420/SimpleClans#247]
im running a 1.7.10 server with simpleclans but i cant seem to figure out how to setup herochat with with simpleclans so that the clan tag appears in next to the players name. what is the format tag that needs to be added to herochat so that the clan tag appears next to the players name?

**Comment by phaed420** [comment]
Have you tried the chat-compatibility-mode in the config?

**Comment by Longhair1996** [comment]
just tried it but the tag is not displaying. before i turned it on i did happen to see my tag when i was changing my players movement speed with essentials

**Comment by phaed420** [comment]
Herochat uses its own chat event, will need to create a separate integration for it.

**Comment by erik1988** [comment]
It works for me.
Simpleclan config:
mchat-integration: true
chat-compatibility-mode: false

This is how my herochat looks like:
format:
  default: '{color}[{nick}]&8{prefix}&7{sender}:&f {msg}'

**Comment by phaed420** [comment]
Thanks Erik!  Saved me some time testing this. :)
