### ISSUE TITLE
Continuous requests

### ISSUE THREAD

**Issue by elevatorpigeon** [phaed420/SimpleClans#248]
Requests continue to spam chat even after acceptance/denial.

**Comment by phaed420** [comment]
What version of SC you using?

**Comment by erik1988** [comment]
It still spams in build 83

**Comment by phaed420** [comment]
Can you give me steps I can follow to reproduce?

**Comment by erik1988** [comment]
When you tried to fix the problem last time it was only spamming the console, but the player saw no reqest after they had answered. Now atfer that build, it is spamming the leaders chat.

I think all you need to do is to use spigot 1.8.3 and have someone send you an ally request. no matter if you accept or deny, you will still see the request popping back until the server restarts.

**Comment by erik1988** [comment]
It works now. Thanks :)
