### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by Her-Craving** [phaed420/SimpleClans#257]
I have extreme on my server being caused by the  Task: RequestManager$1(interval 1200)

Here is my timings report: http://timings.aikar.co/?url=10768520

**Comment by phaed420** [comment]
What do you have *request.ask-frequency-secs* set to in the config?

**Comment by Her-Craving** [comment]
60

**Comment by Her-Craving** [comment]
Has this been tested? Where can I download a version with a fix?

**Comment by phaed420** [comment]
Not yet tested.  http://repo.sacredlabyrinth.net:8080/
