### ISSUE TITLE
clan sethome not taking money

### ISSUE THREAD

**Issue by mohannadi** [phaed420/SimpleClans#258]
I set the config   home-teleport-set-price: 20000
  purchase-home-teleport-set: true but it still doesnt take money from them to set the home but when they do /clan home it costs the appropriate amount set as follows:  home-teleport-price: 150
  purchase-home-teleport: true
The permissions they have is simpleclans.leader.* I tried setting it to false it would still not take money
edit: I am using version 2.5.3

**Comment by phaed420** [comment]
To set home they need the *simpleclans.mod.home* permission.  It was added to the mod group cause if you give this to regular players they may just set base home at someone elses base to spawn kill them.
