### ISSUE TITLE
How....

### ISSUE THREAD

**Issue by DutchUser** [phaed420/SimpleClans#263]
How can i set that clans gave more then 3 rivals?
That there is no limit

Greetz, VocalWolf

**Comment by phaed420** [comment]
Raise the *settings.rival-limit-percent* value.

**Comment by DutchUser** [comment]
Thx, But now i got an other issue.
SimpleClans Version: R: 2.5.3
Server Version: Spigot Snapshot 1.8.3
Issue:
When i do /clan rival remove HeavenH Then i got an console error

Error:
21.04 23:28:26 [Server] INFO java.lang.Thread.run(Unknown Source)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
21.04 23:28:26 [Server] INFO java.util.concurrent.FutureTask.run(Unknown Source)
21.04 23:28:26 [Server] INFO java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
21.04 23:28:26 [Server] INFO net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1125)
21.04 23:28:26 [Server] INFO org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
21.04 23:28:26 [Server] INFO org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
21.04 23:28:26 [Server] INFO org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
21.04 23:28:26 [Server] INFO org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
21.04 23:28:26 [Server] INFO java.lang.reflect.Method.invoke(Unknown Source)
21.04 23:28:26 [Server] INFO sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
21.04 23:28:26 [Server] INFO sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
21.04 23:28:26 [Server] INFO sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21.04 23:28:26 [Server] INFO net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerCommandPreprocess(SCPlayerListener.java:139)
21.04 23:28:26 [Server] INFO net.sacredlabyrinth.phaed.simpleclans.managers.CommandManager.processClan(CommandManager.java:196)
21.04 23:28:26 [Server] INFO net.sacredlabyrinth.phaed.simpleclans.commands.RivalCommand.execute(RivalCommand.java:85)
21.04 23:28:26 [Server] INFO net.sacredlabyrinth.phaed.simpleclans.SimpleClans.getLang(SimpleClans.java:198)
21.04 23:28:26 [Server] INFO java.util.ResourceBundle.getString(Unknown Source)
21.04 23:28:26 [Server] INFO java.util.ResourceBundle.getObject(Unknown Source)
21.04 23:28:26 [Server] INFO SimpleClans command failure: Can't find resource for bundle java.util.PropertyResourceBundle, key your.clans.are.not.rivals

**Comment by phaed420** [comment]
Look at the last line.  Seems you messed up/deleted the language key *your.clans.are.not.rivals*

**Comment by DutchUser** [comment]
Ow. But how i can fix this?

**Comment by phaed420** [comment]
Before anything, you do know that you should not change things on the left side of the equals sign on that file.  If you have then you need to start over making sure you only translate the text on the right side of the equals sign.

If that's not your problem, what you need to do is compare a clean copy of the language file and yours.  Look for *your.clans.are.not.rivals*, if its missing, add it.

**Comment by DutchUser** [comment]
How i can i get an compare a clean copy of the language file?

Because i already re-downloaded an new .Jar ans still i get this probleem.

**Comment by phaed420** [comment]
Hmm, let me check.

**Comment by DutchUser** [comment]
and also stop the server for 2 times now (and start) and still i get the issue.
Must i also let the plugin re-create an config file and db?

**Comment by phaed420** [comment]
it was missing
