### ISSUE TITLE
WorldGuard and MCTowns

### ISSUE THREAD

**Issue by doitliketyler** [phaed420/SimpleClans#266]
I noticed you mentioned the WorldGuard addon in the description. I use MCTowns and it uses WorldGuard for protection so is it safe to assume that with this future addon that when war is accepted between two MCTown's that they would be unprotected? If so then awesome :)

**Comment by phaed420** [comment]
Probably not, this war functionality would need to be added in.

**Comment by doitliketyler** [comment]
I recently realized that Residence does what MCTown's does but better so I moved to that. Thanks for getting back to me regardless.

**Comment by phaed420** [comment]
Cool
