### ISSUE TITLE
Tab to complete names doesn't work

### ISSUE THREAD

**Issue by Her-Craving** [phaed420/SimpleClans#269]
Pressing tab to complete names does not work when using simpleclans commands. It would make it much easier.

**Comment by Her-Craving** [comment]
It doesn't really work. I can only press tab to go through all the names, it doesn't auto-complete the name i'm in the middle of typing out

**Comment by phaed420** [comment]
Which command are you testing? Can you post the exact thing you type before you press tab?

**Comment by Her-Craving** [comment]
/clan lookup mi (then i press tab) and it completes to "gioboi" instead of "MissMarzBarz_"

Only Gioboi (me) and MissMarzBarz_ are online

**Comment by Her-Craving** [comment]
Thanks! I'm really glad you're fixing up the plugin. It's running smoothly now with no lag.

**Comment by phaed420** [comment]
:)

**Comment by Her-Craving** [comment]
Something you did isn't allowing people to join clans. I'm using the newest build (99). You can invite someone, they can accept, it says they joined, but they aren't actually in the clan. Players that weren't already in a clan can't use any /clan command. The people that are now invited to clans don't have the tags as well.

**Comment by phaed420** [comment]
Pheww, great.  That sounded scary as fuck.

**Comment by Her-Craving** [comment]
Yeah it was scary, but something you did actually did break the /more command haha
