### ISSUE TITLE
Clan join request spamming players

### ISSUE THREAD

**Issue by Her-Craving** [phaed420/SimpleClans#274]
If players don't /accept or /deny a request, they will continue to be asked until they type one. It would be nice if this was just a one time message.

**Comment by phaed420** [comment]
There is a setting *requests.max-asks-per-request* in the new builds that you can use to limit that.

**Comment by Her-Craving** [comment]
Thanks. Sorry about that. Do I just set   max-asks-per-request: to 1?

**Comment by phaed420** [comment]
Correct.
